# Generated by Django 3.1.2 on 2020-10-27 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('logo', models.ImageField(default='static/no-image.png', upload_to='company_logo')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('photo', models.ImageField(default='static/no-image.png', upload_to='product_pics')),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('I Category', '1'), ('II Category', '2'), ('III Category', '3'), ('IV Category', '4'), ('V Category', '5'), ('VI Category', '6')], max_length=256)),
                ('schooltype', models.CharField(choices=[('praktijkonderwijs', 'praktijkonderwijs'), ('vmbo', 'vmbo'), ('mbo', 'mbo'), ('hbo', 'hbo'), ('opleidingsbedrijf', 'opleidingsbedrijf')], max_length=256)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='products.company')),
            ],
        ),
    ]
